### ISSUE TITLE
Colored circles??

### ISSUE THREAD

**Issue by Erhannis** [JoanSchi/flextable#2]
So uh, what do the colored circles in the bottom right mean?  What do they do?  And can we turn them off?

**Comment by JoanSchi** [comment]
Only in debug mode for debugging I will turn it off.  With autofreeze the table is using one or to panels depending on the scroll position. The panels with most cell is kept to prevent a jank and the therefore the panels need to change position. With the colored circles I could easily check this.

**Comment by Erhannis** [comment]
Ah, I see; thanks
